version: '2'
services:
  sinusbot:
    image: sinusbot/docker
    restart: always
    ports:
      - 8087:8087
    volumes:
      - ./scripts:/opt/sinusbot/scripts
      - ./data:/opt/sinusbot/data
    network:
      - ts3_ts3
networks:
  ts3_ts3:
    external: true
